### ISSUE TITLE
Protein PDB files contain only CA atoms instead of all the heavy atoms

### ISSUE THREAD

**Issue by yipy0005** [shuyana/DiffusionProteinLigand#1]
Dear Authors,

Thank you so much for developing this AI model. It has been a valuable tool for my research and I am very grateful for your hard work and dedication.

I noticed that the predicted output only contains CA atoms and not any other heavy atoms. I understand that this may be a limitation of the current model, but I would very much appreciate if you could look into this issue.

Thank you again for your contributions to the field and I look forward to any updates or improvements to the model.

Sincerely,
Yew Mun

**Comment by shuyana** [comment]
Dear Yew Mun,
Thank you for trying our models and for your comment.

Unfortunately, it is one of the major limitations of the current model that only the CA atoms are supported, as you mentioned and as discussed in our paper.
We understand that modeling all heavy atoms of the protein is crucial for better interpretation and practical use, and we are working on it with high priority.

We appreciate your interest.
Closing, as this is an expected behavior at this point.

Kind regards,
Shuya Nakata.
